name: Pull Request Check

on: [push, pull_request]

jobs:
  prcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      # 读取 gofumpt 二进制文件缓存
      - name: Cache gofumpt binary
        id: cache-gofumpt  # 添加 id 字段
        uses: actions/cache@v3
        with:
          path: ${{ env.$GOPATH }}/bin/gofumpt
          key: ${{ runner.os }}-gofumpt
          restore-keys: |
            ${{ runner.os }}-gofumpt

      # 如果无缓存则下载
      - name: Install gofumpt
        if: steps.cache-gofumpt.outputs.cache-hit != 'true'
        run: |
          go install mvdan.cc/gofumpt@latest

      # 打印 GOPATH
      - name: Print GOPATH
        run: echo $GOPATH

      # 验证 gofumpt 是否安装成功
      - name: Verify gofumpt installation
        run: |
          if [ -f $GOPATH/bin/gofumpt ]; then
            echo "gofumpt is installed at $GOPATH/bin/gofumpt"
          else
            echo "gofumpt is not installed"
          fi