name: Pull Request Check

on: [pull_request,push]

jobs:
  prcheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      # 读取 gofumpt 二进制文件缓存
      - name: Cache gofumpt binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/gofumpt
          key: ${{ runner.os }}-gofumpt
          restore-keys: |
            ${{ runner.os }}-gofumpt

      # 如果无缓存则下载
      - name: Install gofumpt
        if: steps.cache-gofumpt.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          GOBIN=~/.local/bin go install mvdan.cc/gofumpt@latest
          